# Configuração do Prometheus para BeeCatalog
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Django application metrics
  - job_name: 'django-beecatalog'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Django dev server
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s

  # Celery metrics (via Flower)
  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/api/workers'
    scrape_interval: 60s

  # Node Exporter (if running on host)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules for common queries
rule_files:
  - "beecatalog_rules.yml"